#!/usr/bin/env bash
# Metadata-scan change must be bit-exact vs the previous build's output. We can't A/B the build
# with an env knob, so compare greedy tokens against the saved reference from tie_check
# (/tmp/tie_seq.pt was generated by the pre-change build with EXL3_HIP_GR_MIX_Q8=0) and run PPL.
set -u
cd ~/exllamav3-amd && source tools/strix_halo/env.sh >/dev/null 2>&1
export EXL3_MOE_CFG=2 EXL3_HIP_PREFILL_MIN_ROWS=2
echo "=== greedy noise floor (also exercises new metadata kernel twice) ==="
.venv/bin/python tools/strix_halo/greedy_ab.py EXL3_MOE_CFG 2 2 2>&1 | grep -v Warning
echo "=== PPL ==="
.venv/bin/python eval/ppl.py -m ~/models/Qwen3.8-Flash-Next-EXL3 -r 20 -l 1024 > /tmp/ppl_meta.raw 2>&1
grep -iE "perplexity" /tmp/ppl_meta.raw | tail -1
echo "=== 6-prompt ndt=2 ==="
NDT=2 DC=0.4 .venv/bin/python tools/strix_halo/prompt_sweep.py 2>&1 | tail -3
echo DONE
